admin.product.delete:
  path: admin/product/{id}/delete
  defaults:
    _title: Amin | Create Shop
    _form: ntc\product\form\ProductForm
    _model: app\core\entity\Product.delete
  requirements:
    id: \d+
    _permission: administer actions

admin.product.create:
  path: admin/product/add
  defaults:
    tab: Information
    _title: Amin | Product
    _form: ntc\product\form\ProductForm
    _model: app\core\entity\Product.create
  requirements:
    tab: .+
    _permission: administer actions

admin.product.edit:
  path: admin/product/{id}/edit
  defaults:
    tab: information
    _title: Amin | Product
    _form: ntc\product\form\ProductForm
    _model: app\core\entity\Product.update
    id: 1
  requirements:
    tab: .+
    id: \d+
    _permission: administer actions

admin.product.list:
  path: admin/product/list
  defaults:
    _title: Amin | User Shop List
    _list: ntc\product\listing\ProductList
    _model: app\core\entity\Product
  requirements:
    _permission: administer actions

product.index:
  path: product/{id}/{url}
  defaults:
    id: 0
    url: default
    _controller: ntc\product\controller\ProductController::index
  requirements:
    id: \d+
    url: .+
  options:
    _shop_route: true