admin.product:
  path: admin/product
  defaults:
    name: ~
    _title: Amin | Product
    _controller: ntc\product\controller\ProductController::index
  requirements:
    _permission: administer actions

admin.product.add:
  path: admin/product/add
  defaults:
    tab: Information
    _title: Amin | Product
    _form: ntc\product\form\ProductForm
    _model: app\core\entity\Product.create
  requirements:
    tab: .+
    _permission: administer actions
#
#admin.product.add:
#  path: admin/product/add/{tab}
#  defaults:
#    tab: Information
#    _title: Amin | Product
#    _controller: ntc\product\controller\ProductController::add
#  requirements:
#    tab: .+
#    _permission: administer actions

admin.product.edit:
  path: admin/product/{entity}/edit
  defaults:
    tab: information
    _title: Amin | Product
    _form: ntc\product\form\ProductForm
    _model: app\core\entity\Product.update
    entity: 1
  requirements:
    tab: .+
    entity: \d+
    _permission: administer actions

