name: Product
type: module
description: 'Manages products in a shop'
package: ntc\product
# version: VERSION
# core: 8.x
configure: admin.settings
dependencies:
  required:
  - administrator
  - user
  - shop
  optional:
  - user

