admin.product.delete:
  path: admin/product/{id}/delete
  defaults:
    _title: Admin | Delete Product
    _form: ntc\product\form\ProductForm
    _model: app\core\entity\Product.delete
  requirements:
    id: \d+
    _permission: administer actions

admin.product.create:
  path: admin/product/add
  defaults:
    _title: Admin | Product
    _form: ntc\product\form\ProductForm
    _model: app\core\entity\Product.create
  requirements:
    _permission: administer actions

admin.product.edit:
  path: admin/product/{id}/edit
  defaults:
    tab: information
    _title: Admin | Edit Product
    _form: ntc\product\form\ProductForm
    _model: app\core\entity\Product.update
#    id: 1
  requirements:
    tab: .+
    id: \d+
    _permission: administer actions

admin.products:
  path: admin/products
  defaults:
    _title: Admin | Product List
    _list: ntc\product\listing\ProductList
    _model: app\core\entity\Product
  requirements:
    _permission: administer actions

product.index:
  path: shop/{shop_url}/product/{product_id}/{product_url}
  defaults:
    product_id: 0
    product_url: default
    _controller: ntc\product\controller\ProductController::index
  requirements:
    shop_url: "[a-zA-Z0-9-_/]+"
    product_id: \d+
    product_url: .+
  options:
    _shop_route: true

  # image routes
admin.product.image.upload:
    path: /admin/product/image/upload
    defaults:
      _controller: ntc\product\form\ProductForm::ajaxUploadImage
admin.product.image.delete:
    path: /admin/product/image/delete/{id}
    defaults:
      _controller: ntc\product\form\ProductForm::ajaxDeleteImage
admin.product.image.temp.url:
    path: /app/modules/product/uploads/tmp/{name}
    defaults:
      _controller: ntc\product\form\ProductForm::ajaxUploadImage
admin.product.image.url:
  path: /app/modules/product/uploads/{id}/{name}
  defaults:
    _controller: ntc\section\form\ProductForm::ajaxUploadImage