product.add:
  version: VERSION
  js:
    comment-entity-form.js: {}
  dependencies:
    - core/jquery
    - core/drupal
    - core/drupal.form
product.cart:
  js:
    product.js: {}
  version: 1.0.0
  dependencies:
