<?php

namespace app\core\entity\repository;

/**
 * ActvityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ActvityRepository extends \Doctrine\ORM\EntityRepository
{
}
