<?php

namespace app\core\entity\repository;

use Doctrine\ORM\EntityRepository;

/**
 * ProductImageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductImageRepository extends EntityRepository
{
}
