<?php

namespace app\core\entity\repository;

use Doctrine\ORM\EntityRepository;

/**
 * RoleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RoleRepository extends EntityRepository
{
    public function getUserPermisions($user_id = 0, $shop_id = 0)
    {
//        $query = $this->getEntityManager()->createQuery('SELECT r.permissions FROM Role r WHERE r.id_shop = '.$shop_id);
//        if (!isset($shop_id) || !isset($user_id)) {
//            $user_id = 0;
//            $shop_id = 0;
//        }
        $query = $this->getEntityManager()->createQuery("SELECT r.permissions FROM {$this->getEntityName()} r" .
            " JOIN r.users u WHERE r.shop ={$shop_id} AND u.id = {$user_id}");
        $users = $query->getResult();
//        $users = $query->getDQL();

//        $users = $this->findOneBy(['shop' => 1, 'users' => [1]]);
        return $users;
    }
}