<?php

namespace app\core\entity\repository;

use Doctrine\ORM\EntityRepository;

/**
 * RoleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RoleRepository extends EntityRepository {
    public function getUserPermisions($user_id, $shop_id) {
//        $query = $this->getEntityManager()->createQuery('SELECT r.permissions FROM Role r WHERE r.id_shop = '.$shop_id);
//        $users = $query->getResult();

        $users = $this->findBy(['shop' => 1]);
        dump($users);
        return $users;
    }
}