<?php

namespace app\core\entity\repository;

use Doctrine\ORM\EntityRepository;

/**
 * SectionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SectionRepository extends EntityRepository {
    public function getShopSections($idShop, $default = false) {
        $fields = array('s.id', 's.name'/*, 'o.id'*/);
//$fields = 'partial s.{id, name}, partial o.{id}';  //if you want to get entity object

        $query = $this->getEntityManager()->createQueryBuilder();
        $or = $query->expr()->orX();
        $or->add($query->expr()->eq('s.shop', $idShop));
//        $or->add($qb->expr()->eq('u.id', 2));
        $query
          ->select($fields)
          ->from($this->getClassName(), 's')
//            ->leftjoin('s.otherEntity', 'o');
          ->where($or);

//        $query->setMaxResults(10);
        $results = $query->getQuery()->getResult();
        $return = [];
//        if ($default)
//            $return += [0 => 'default section'];
        foreach ($results as $result) {
            $return += [$result['id'] => $result['name']];
        }
        return $return;
    }
}
