<?php

namespace app\core\entity\repository;

/**
 * SectionImageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SectionImageRepository extends \Doctrine\ORM\EntityRepository
{
}
