regions:
    header_left:
        - ntc\administrator\brand
        - ntc\administrator\search
    header_right:
        - ntc\administrator\notification
        - ntc\administrator\userinfo
    breadcrumb: null
    help: null
    sidebar:
        - ntc\administrator\sidebar
    footer: null