regions:
  header_left:
    - ntc\administrator\brand
    - ntc\administrator\search
#    - ntc\administrator\quickaccess
  header_right:
    - ntc\administrator\notification
    - ntc\administrator\userinfo
  breadcrumb:

  help:
  sidebar:
    - ntc\administrator\sidebar
#  container: Container
  footer: