<?php

define('_ADMIN_COMPONENT_DIR_', _ROOT_DIR_ . 'admin/component' . '/');
define('_ADMIN_THEME_DIR_', _ADMIN_DIR_ . 'theme' . DIRECTORY_SEPARATOR);
define('_ADMIN_THEME_JS_DIR_', _ADMIN_THEME_DIR_ . 'js' . DIRECTORY_SEPARATOR);
define('_ADMIN_THEME_CSS_DIR_', _ADMIN_THEME_DIR_ . 'css' . DIRECTORY_SEPARATOR);
define('_ADMIN_THEME_FONT_DIR_', _ADMIN_THEME_DIR_ . 'font' . DIRECTORY_SEPARATOR);
//var_dump(_ADMIN_THEME_DIR_);
