<?php

define('_PAGE_ADMIN_DIR_', _PAGE_DIR_ . DIRECTORY_SEPARATOR . 'admin' . DIRECTORY_SEPARATOR);
define('_THEME_ADMIN_DIR_', _THEME_DIR_ . 'admin' . DIRECTORY_SEPARATOR);
define('_THEME_ADMIN_JS_DIR_', _THEME_DIR_ . 'admin' . DIRECTORY_SEPARATOR);
define('_THEME_ADMIN_CSS_DIR_', _THEME_DIR_ . 'admin' . DIRECTORY_SEPARATOR);
define('_THEME_ADMIN_FONT_DIR_', _THEME_DIR_ . 'admin' . DIRECTORY_SEPARATOR);
