Product:
    type: entity
    table: Product
    indexes:
        product_price_name_idx:
            columns:
                - id
                - price
                - name
    uniqueConstraints:
        UNIQ_1CF73D31F3EED39F:
            columns:
                - id_section
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        name:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
                comment: 'Product''s name'
        shortDescription:
            type: text
            nullable: false
            length: 65535
            options:
                fixed: false
                comment: 'Product''s short description'
            column: short_description
        description:
            type: text
            nullable: false
            length: 65535
            options:
                fixed: false
                comment: 'Product''s long description'
        condition:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
                comment: 'Product''s condition'
                default: new
        type:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
                comment: 'Product''s type'
                default: simple
        available:
            type: boolean
            nullable: false
            options:
                comment: 'Product''s availability'
        price:
            type: decimal
            nullable: false
            precision: 10
            scale: 4
            options:
                comment: 'Product''s price'
        showPrice:
            type: boolean
            nullable: false
            options:
                comment: 'if the price should be shown'
            column: show_price
        onlineOnly:
            type: boolean
            nullable: false
            options:
                comment: 'if the product should be shown online only'
            column: online_only
        active:
            type: boolean
            nullable: false
        created:
            type: datetime
            nullable: false
        updated:
            type: datetime
            nullable: false
    manyToOne:
        idSection:
            targetEntity: Section
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                id_section:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
