params:
  default-class:
    region
regions:
  header_top:
    - ntc_hotline
    - ntc_account
  header_bottom:
    - ntc_logo
    - ntc_navigation
    - ntc_search
    - ntc_cart
  banner:
    - ntc_slider
  highlight:
  siderbar:
    - sections
    - price_range
    - top_rates_product
    - brand filter
    - ads 4:7
  container:
    name: Container
  footer:
    - about
    - ntc_account
    - information
    - contacts
  copy_selection:
    - custom
