params:
  default-class:
    region
regions:
  header_top:
    - ntc\hotline
    - ntc\account
  header_bottom:
    - ntc\logo
    - ntc\navigation
    - ntc\search
    - ntc\cart
  banner:
#    - ntc\slider
  highlight:
  siderbar:
    - sections
    - price\range
    - top\rates\product
    - brand filter
    - ads 4:7
  container:
    name: Container
  footer:
    - about
    - ntc\account
    - information
    - contacts

