params:
  default-class:
    region
regions:
#  usernav:
#    - ntc\user\topnav
  header_top:
#    - ntc\shop\hotline
#    - ntc\shop\account
  header_bottom:
#    - ntc\shop\logo
    - ntc\shop\navigation
#    - ntc\shop\search
#    - ntc\shop\cart
  breadcrumb:
#    - ntc\shop\breadcrumb
  highlight:
  sidebar:
#    - ntc\section\sections
#    - ntc\section\pricerange
#    - top\rates\product
#    - brand filter
#    - ads 4:7
  container:
    name: Container
  footer:
#    - about
#    - ntc\shop\account
#    - information
#    - contacts
shop:
  components:
    -kdk

section:
  components:
    -

product:
  components:
    -