<?php

namespace app\core\entity_doctrine\repository;

use Doctrine\ORM\EntityRepository;

/**
 * SectionImageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SectionImageRepository extends EntityRepository
{
}
