<?php

namespace app\core\entity_doctrine\repository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends BaseRepository
{
    public function getRole($shopID)
    {
        $query = $this->getEntityManager()->createQuery("SELECT r.permissions FROM {$this->getEntityName()} r" .
            " JOIN r.users u WHERE r.shop ={$shopID} AND u.id = {$user_id}");
        $users = $query->getResult();
//        $users = $query->getDQL();

//        $users = $this->findOneBy(['shop' => 1, 'users' => [1]]);
        return $users;

    }
}
