<?php

namespace model;

/**
 * RouterRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RouterRepository extends \Doctrine\ORM\EntityRepository {

  public function deleteAll() {
    foreach ($this->findAll() as $entity) {
      $this->getEntityManager()->remove($entity);
    }
    $this->getEntityManager()->flush();
  }

}
