params:
  default-class:
    region
regions:
  top_bar:
    - ntc\shop\search
    # - ntc\shop\hotline
    - ntc\shop\account
  navbar:
    - ntc\shop\logo
    - ntc\shop\navigation
    # - ntc\shop\cart
  slider:
#    - ntc\shop\slider
  headerText:
  sidebar:
    # - ntc\section\sections
    # - ntc\section\pricerange
    # - top\rates\product
    # - brand filter
    # - ads 4:7
  content:
#    name: Container
     - ntc\shop\featured
  footer:
    # - about
    # - ntc\shop\account
    # - information
    # - contacts
shop:
  components:
    -kdk

section:
  components:
    -

product:
  components:
    -
